;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Item.Type.Passive.StaticDischarge",DevComment="")
GameplayTagList=(Tag="Item.Type.Weapon.Aura",DevComment="")
GameplayTagList=(Tag="Item.Type.Weapon.Axe",DevComment="")
GameplayTagList=(Tag="Item.Type.Weapon.Boomerang",DevComment="")
GameplayTagList=(Tag="Item.Type.Weapon.Bow",DevComment="")
GameplayTagList=(Tag="Item.Type.Weapon.Lightning",DevComment="")
GameplayTagList=(Tag="Item.Type.Weapon.Rocks",DevComment="")
GameplayTagList=(Tag="Item.Type.Weapon.Sword",DevComment="")

